name: ♻️ Update Profile README

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 9:30 AM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Profile Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable default GitHub token
          fetch-depth: 0              # Needed for pushing

      - name: Update README Date
        run: |
          set -x
          TODAY=$(TZ=Asia/Kolkata date +"%A, %d %B %Y")
          sed -i "s|<!--date-->.*<!--/date-->|<!--date--> $TODAY <!--/date-->|" README.md
          cat README.md

      - name: Commit and Push if Changed
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "elliee-bot"
          git config --global user.email "elliee@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git diff --quiet README.md || (
            git add README.md
            git commit -m "🔄 Daily README refresh"
            git push origin main
          )
